name: deploy to Server

on:
  push:
    branches: [ "main" ]

#temp env var while i test the website on my server
env:
  NODE_ENV: pages
#temp ends

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: 'npm'
      - name: NPM install
        run: npm ci
      - name: NPM build
        run: npm run build --if-present
      - name: Copy artifact to server
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.WEB_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          source: 'dist/*'
          target: /home/pi/cv-resume
